### PR TITLE
Populated the database with dumby data

### PR DESCRIPTION
**Pull request by hfrankst**
# Populated Database with Dumby Data

## Status
Ready

## Description
This pull request contains a json file that holds all of the database's company data.  

### Related Tickets 
***

[Populate Database with Company Data](https://github.com/illegal-llamas/Bangazon-LLC/issues/2)

### Impacted Areas of the Application
***
Files that this PR modifies or affects in some way. 
```
    models.py
    db.json
    db.sqlite3
```

### Deploy Notes
***
Follow the below instructions to pull down the code. Once you have launched the server, click into the list views of all tables to ensure that they are populated correctly. 
```
    git pull 
    git fetch --all
    git checkout hf-databaseWork
    python manage.py makemigrations
    python manage.py migrate
    python manage.py migrate --run-syncdb
    python manage.py loaddata initial_data.json
    python manage.py runserver
```

### CODE REVIEW

**Comment by kayrahbear** [comment]
For some reason your JSON file is encoded in UTF 16, instead of 8, and can't be loaded into the database. Try converting to UTF 8 and re-uploading 😄

**Comment by thenicknash** [comment]
Much beauty. Such wow.

**Comment by jnelsontn** [comment]
Works fine.

**Comment by thenicknash** [comment]
:shipit:

**Comment by kayrahbear** [comment]
Excellent update to the run instructions. Everything working great on my machine. :shipit:

**Pull request merged**
