### PR TITLE
created the join table for the product order relationship

### PR DESCRIPTION
**Pull request by hfrankst**
# ProductOrder Join Table Data Entry

## Status
Ready

## Description
The json for the table describing the relationship between the products and orders.

### Related Tickets 
***
List all related tickets that are addressed by this pull request

[Data Entry Ticket](https://github.com/illegal-llamas/Bangazon-LLC/issues/59)

### Impacted Areas of the Application
***
File created:
```
    product_order.json
```

### Deploy Notes
***
Follow the steps below to test the code:

```
    git pull 
    git fetch --all
    git checkout hf-productOrder
    python manage.py makemigration
    python manage.py migrate
    python manage.py loaddata bangazon/api/fixtures/product_order.json
    python manage.py runserver
```

### CODE REVIEW

**Comment by jnelsontn** [comment]
👍

**Comment by kayrahbear** [comment]
Truly you are a master of the JSON good sir. However, your FKs don't need quotes

**Comment by kayrahbear** [comment]
Looks good now!

**Comment by jnelsontn** [comment]
Looks good 💯

**Pull request merged**
