### PR TITLE
Hf expose order info

### PR DESCRIPTION
**Pull request by hfrankst**
# Completed the Orders and Department Tables

## Status
Ready 

## Description
The purpose of this pull request is to test the code responsible for the creation of the Order and Department tables.

### Related Tickets 
***

[Expose Order Information to API Ticket](https://github.com/illegal-llamas/Bangazon-LLC/issues/8)
[Expose Department Information to API Ticket](https://github.com/illegal-llamas/Bangazon-LLC/issues/6)

### Impacted Areas of the Application
***

```
    models.py
    views.py
    urls.py
    serializers.py
    db.sqlite
    
```

### Deploy Notes
***
To test this code, follow the instructions below. Be sure to click on the urls to see that the Orders List and Department List views are working.

```
    git pull 
    git fetch --all
    git checkout hf-exposeOrderInfo
    python manage.py makemigration
    python manage.py migrate
    python manage.py runserver
```

### CODE REVIEW

**Comment by jnelsontn** [comment]
Successfully runs with correct database table.

**Review by thenicknash — COMMENTED** [review]
Just absolutely fantastic! Works like a charm 🌮

**Comment by jnelsontn** [comment]
Perfect. Close it.

**Comment by caseydailey** [comment]
:shipit:

**Pull request merged**
