### PR TITLE
added copious amounts of docstrings

### PR DESCRIPTION
**Pull request by caseydailey**
# Docstrings all around!

## Status
READY

## Description
In pursuit of the definition of done, I've added docstrings to all classes and methods 

### Related Tickets 
***
https://github.com/illegal-llamas/Bangazon-LLC/issues/40

### Impacted Areas of the Application
***
Files that this PR modifies or affects in some way. 
```
        modified:   bangazon/api/models.py
	modified:   bangazon/api/serializers.py
	modified:   bangazon/api/views.py
	modified:   bangazon/urls.py
```

### Deploy Notes
***
just review the above files here on github to verify the docstrings are there

### CODE REVIEW

**Comment by thenicknash** [comment]
Works like a charm! Just fix the indentation!

**Comment by kayrahbear** [comment]
Indentation errors! 😿

**Comment by caseydailey** [comment]
i've corrected the indent errors and have run it on my server. should be good to go, but do please run it on yours to confirm

**Comment by kayrahbear** [comment]
All better! Works great on my machine! :shipit:

**Comment by jnelsontn** [comment]
🦑 Works.

**Pull request merged**
